services:
  - type: web
    name: iamblank
    runtime: static
    branch: main
    buildCommand: npm install -g pnpm && pnpm install && pnpm --filter @workspace/iamblankworkspace run build
    staticPublishPath: ./artifacts/iamblankworkspace/dist/public
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_PATH
        value: /
      - key: PORT
        value: 3000
